import type { Metadata } from "next";
import { Inter } from "next/font/google";
// https://authjs.dev/reference/next-auth/react#sessionproviderprops
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

// https://stackoverflow.com/questions/76478043/next-js-always-fail-at-downloading-fonts-from-google-fonts/76484168#76484168
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
